remote_theme: "mmistakes/minimal-mistakes"
show_downloads: false
logo: photo2.jpeg

title: Mads R. Bisgaard
description: Me enjoying life in Mugardos, Galicia.

github:
  is_user_page: false
  is_project_page: false

plugins:
  - jekyll-include-cache