theme: jekyll-theme-minimal
show_downloads: false
logo: photo2.jpeg

title: Mads Bisgaard
description: This is my personal (non-professional) website

github:
  is_user_page: false
  is_project_page: false
