remote_theme: "mmistakes/minimal-mistakes@4.24.0"
show_downloads: false
logo: photo2.jpeg

title: Mads R. Bisgaard
description: Me enjoying life in Mugardos, Galicia.

github:
  is_user_page: false
  is_project_page: false
