theme: jekyll-theme-minimal
show_downloads: false
logo: photo2.jpeg

title: Mads R. Bisgaard
description: Me enjoying life at [one of my favourite locations](https://www.google.com/maps/place/15620+Mugardos,+Provinz+A+Coru%C3%B1a,+Spanien/@43.4605783,-8.2801289,13.75z/data=!4m5!3m4!1s0xd2e7650c8f228ab:0x4240a20a4ceb9cbf!8m2!3d43.4599466!4d-8.2558155)is my personal (non-professional)

github:
  is_user_page: false
  is_project_page: false
