theme: jekyll-theme-minimal
show_downloads: false
logo: photo2.jpeg

title: Mads R. Bisgaard
description: Me enjoying life in Mugardos, Galicia.

github:
  is_user_page: true
  is_project_page: false
